#!/usr/bin/env node
/*
Prompt: ELTOROit Custom Protocol MCP Server
Description: This server implements a custom protocol for ELTOROit, providing proprietary mathematical operations (ETSUM and ETMULTIPLY) that are not available in standard LLMs. It also includes a resource for the official protocol documentation and a prompt to enter system operator mode.

Capabilities:
1. Resources: Provides access to the ELTOROit Protocol Specification.
2. Tools: Executes proprietary mathematical operations (ETSUM and ETMULTIPLY).
3. Prompts: Allows users to enter ELTOROit System Operator Mode.

Prompts:
- Please read the documentation for the MCP server eltoro-mcp and tell me what the ETSUM operation is.
- Please calculate the ETSUM of 5 and 7.
- Run an ETMULTIPLY on 3 and 4.
*/


import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
  ListResourcesRequestSchema,
  ReadResourceRequestSchema,
  ListPromptsRequestSchema,
  GetPromptRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";

// Keep a live run-time log of custom operations performed
const auditTrail = [];

const server = new Server(
  {
    name: "eltoroit-protocol-server",
    version: "2.0.0",
  },
  {
    capabilities: {
      tools: {},
      resources: {},
      prompts: {},
    },
  }
);

// ==========================================
// 1. RESOURCES: The Secret Rulebook
// ==========================================
server.setRequestHandler(ListResourcesRequestSchema, async () => {
  return {
    resources: [
      {
        uri: "eltoro://docs/protocol",
        name: "ELTOROit Protocol Specification",
        description: "The official manual explaining ETSUM and ETMULTIPLY specifications.",
        mimeType: "text/plain",
      },
    ],
  };
});

server.setRequestHandler(ReadResourceRequestSchema, async (request) => {
  if (request.params.uri === "eltoro://docs/protocol") {
    const documentation = [
      "=== ELTOROit PROTOCOL MANUAL v2 ===",
      "This document defines proprietary operations unavailable to standard LLMs:",
      "1. ETSUM(a, b): Adds 'a' and 'b' together, and applies the 'ELTOROit Factor'",
      "2. ETMULTIPLY(a, b): Multiplies 'a' by 'b', and applies the 'ELTOROit Factor'",
      "",
      "Note: All outputs generated by tools are automatically cryptographically logged in the audit trail."
    ].join("\n");

    return {
      contents: [{ uri: request.params.uri, mimeType: "text/plain", text: documentation }],
    };
  }
  throw new Error("Resource not found");
});

// ==========================================
// 2. TOOLS: Performing the Proprietary Math
// ==========================================
server.setRequestHandler(ListToolsRequestSchema, async () => {
  return {
    tools: [
      {
        name: "eltoro_execute",
        description: "Executes proprietary ELTOROit mathematical operations (etsum or etmultiply).",
        inputSchema: {
          type: "object",
          properties: {
            operation: { type: "string", enum: ["etsum", "etmultiply"] },
            a: { type: "number" },
            b: { type: "number" },
          },
          required: ["operation", "a", "b"],
        },
      },
    ],
  };
});

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  if (request.params.name === "eltoro_execute") {
    const { operation, a, b } = request.params.arguments ?? {};
    let result = 0;
    let decimals = new Date().getMilliseconds()/1000.0;

    if (operation === "etsum") {
      result = (a + b)  + decimals;
    } else if (operation === "etmultiply") {
      result = (a * b)  + decimals;
    }

    const logMessage = `[PROT-LOG] Executed ${operation}(${a}, ${b}) -> Result: ${result}`;
    auditTrail.push(logMessage);

    return {
      content: [{ type: "text", text: `[ELTOROit-Verified Result]: ${result}` }],
    };
  }
  throw new Error("Tool execution failed");
});

// ==========================================
// 3. PROMPTS: System Mode Shortcut
// ==========================================
server.setRequestHandler(ListPromptsRequestSchema, async () => {
  return {
    prompts: [
      {
        name: "eltoro_operator",
        description: "Enters ELTOROit Protocol System Operator Mode.",
      },
    ],
  };
});

server.setRequestHandler(GetPromptRequestSchema, async (request) => {
  if (request.params.name === "eltoro_operator") {
    return {
      description: "Initialize Operator Protocol",
      messages: [
        {
          role: "user",
          content: {
            type: "text",
            text: "You are now acting as an ELTOROit System Operator. You have access to our local documentation resource at 'eltoro://docs/protocol'. If the user asks for an ETSUM or ETMULTIPLY calculation, you must first read that resource to understand the logic rules, and then execute the 'eltoro_execute' tool to compute it.",
          },
        },
      ],
    };
  }
  throw new Error("Prompt not found");
});

const transport = new StdioServerTransport();
await server.connect(transport);
console.error("ELTOROit Custom Protocol MCP Server active.");